chore: change file extensions because of GitHub limitations

diff --git a/.github/workflows/lint.yaml b/.github/workflows/lint.yaml
--- a/.github/workflows/lint.yaml
+++ b/.github/workflows/lint.yaml
@@ -39,8 +39,12 @@ jobs:
         uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
 
       - name: "Check for .yml extensions"
+        env:
+          EXCLUDE: '\.github/ISSUE_TEMPLATE/config\.yml'
         run: |
-          find . -type f -name "*.yml" | grep . && { echo "Error: Use .yaml instead of .yml"; exit 1; } || exit 0
+          find . -type f -name "*.yml" | \
+            grep -v "$EXCLUDE" | \
+            grep . && { echo "Error: Use .yaml instead of .yml"; exit 1; } || exit 0
 
       - name: "Install yamllint"
         run: pip install yamllint==${{ env.YAMLLINT_VERSION }}
